site_name: SKYVIV
theme:
  name: material
  palette:
    primary: white
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Overview: index.md
  - Accounting:
      - การสร้างข้อมูลหลัก: Accounting/ac01_masterdata.md
      - การบันทึกรายได้และตั้งหนี้ลูกหนี้: Accounting/ac02_invoices.md
      - การบันทึกค่าใช้จ่ายและตั้งหนี้เจ้าหนี้: Accounting/ac03_vendorbill.md
      - การบันทึกจ่ายชำระ: Accounting/ac04_vendorpayment.md
      - การโอนค่าใช้จ่ายเข้าสินค้าคงเหลือ: Accounting/ac05_landedcost.md
  - Purchase:
      - การสร้างคำขอใบเสนอราคา (RFQ): Purchase/Purchase01_RFQ.md
      - การยืนยันคำสั่งซื้อ (Purchase Order): Purchase/Purchase02_PO.md
      - การรับสินค้าเข้าคลัง (Stock IN): Purchase/Purchase03_IN.md
  - Sales:
      - การสร้างใบเสนอราคา (Quotation): Sales/Sales01_Quotation.md
      - การยืนยันคำสั่งขาย (Sales Order): Sales/Sales02_SO.md
      - การส่งสินค้าออกจากคลัง (Stock OUT): Sales/Sales03_OUT.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
