site_name: SKYVIV
theme:
  name: material
  palette:
    primary: white
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Overview: index.md
  - Accounting:
      - การสร้างข้อมูลหลัก: Accounting/ac01_masterdata.md
      - การบันทึกรายได้และตั้งหนี้ลูกหนี้: Accounting/ac02_invoices.md
      - การบันทึกค่าใช้จ่ายและตั้งหนี้เจ้าหนี้: Accounting/ac03_vendorbill.md
      - การบันทึกจ่ายชำระ: Accounting/ac04_vendorpayment.md
      - การโอนค่าใช้จ่ายเข้าสินค้าคงเหลือ: Accounting/ac05_landedcost.md
  - Purchase:
      - เทสๆๆ: Purchase/topic_1.md
      - Topic 2: Purchase/topic_2.md
  - Sales:
      - Topic 1: Sales/topic_1.md
      - Topic 2: Sales/topic_2.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
